# Generated by Django 6.0.6 on 2026-07-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
    ]
