# Generated by Django 6.0.6 on 2026-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('student_class', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('joining_date', models.DateField()),
                ('due_day', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
